;/*FB_PKG_DELIM*/

__d("DirectRequestsThreadAllowFalcoEvent",["FalcoLoggerInternal","getFalcoLogPolicy_DO_NOT_USE"],(function(a,b,c,d,e,f,g){"use strict";a=c("getFalcoLogPolicy_DO_NOT_USE")("3674");b=d("FalcoLoggerInternal").create("direct_requests_thread_allow",a);e=b;g["default"]=e}),98);
__d("MLCHealthLoggerEvent",["$InternalEnum"],(function(a,b,c,d,e,f){a=b("$InternalEnum")({DAILY_INTERACTION_WITH_SURFACE:"daily_interaction_with_surface",COMMIT_CREATE:"commit_create",COMMIT_EDIT:"commit_edit"});c=a;f["default"]=c}),66);
__d("MlcHealthBizappEventFalcoEvent",["FalcoLoggerInternal","getFalcoLogPolicy_DO_NOT_USE"],(function(a,b,c,d,e,f,g){"use strict";a=c("getFalcoLogPolicy_DO_NOT_USE")("2646");b=d("FalcoLoggerInternal").create("mlc_health_bizapp_event",a);e=b;g["default"]=e}),98);
__d("MlcHealthFacebookAndWorkplaceEventFalcoEvent",["FalcoLoggerInternal","getFalcoLogPolicy_DO_NOT_USE"],(function(a,b,c,d,e,f,g){"use strict";a=c("getFalcoLogPolicy_DO_NOT_USE")("2647");b=d("FalcoLoggerInternal").create("mlc_health_facebook_and_workplace_event",a);e=b;g["default"]=e}),98);
__d("MlcHealthFacebookEventFalcoEvent",["FalcoLoggerInternal","getFalcoLogPolicy_DO_NOT_USE"],(function(a,b,c,d,e,f,g){"use strict";a=c("getFalcoLogPolicy_DO_NOT_USE")("2648");b=d("FalcoLoggerInternal").create("mlc_health_facebook_event",a);e=b;g["default"]=e}),98);
__d("MlcHealthInstagramEventFalcoEvent",["FalcoLoggerInternal","getFalcoLogPolicy_DO_NOT_USE"],(function(a,b,c,d,e,f,g){"use strict";a=c("getFalcoLogPolicy_DO_NOT_USE")("3766");b=d("FalcoLoggerInternal").create("mlc_health_instagram_event",a);e=b;g["default"]=e}),98);
__d("MlcHealthInternalToolsEventFalcoEvent",["FalcoLoggerInternal","getFalcoLogPolicy_DO_NOT_USE"],(function(a,b,c,d,e,f,g){"use strict";a=c("getFalcoLogPolicy_DO_NOT_USE")("2649");b=d("FalcoLoggerInternal").create("mlc_health_internal_tools_event",a);e=b;g["default"]=e}),98);
__d("MlcHealthMessagingLightswitchEventFalcoEvent",["FalcoLoggerInternal","getFalcoLogPolicy_DO_NOT_USE"],(function(a,b,c,d,e,f,g){"use strict";a=c("getFalcoLogPolicy_DO_NOT_USE")("2650");b=d("FalcoLoggerInternal").create("mlc_health_messaging_lightswitch_event",a);e=b;g["default"]=e}),98);
__d("MlcHealthWorkplaceEventFalcoEvent",["FalcoLoggerInternal","getFalcoLogPolicy_DO_NOT_USE"],(function(a,b,c,d,e,f,g){"use strict";a=c("getFalcoLogPolicy_DO_NOT_USE")("2651");b=d("FalcoLoggerInternal").create("mlc_health_workplace_event",a);e=b;g["default"]=e}),98);
__d("MLCHealthInstrumentationPlugin__INTERNAL.react",["Lexical","LexicalComposerContext","LexicalUtils","MLCInstrumentationCommands","MlcHealthBizappEventFalcoEvent","MlcHealthFacebookAndWorkplaceEventFalcoEvent","MlcHealthFacebookEventFalcoEvent","MlcHealthInstagramEventFalcoEvent","MlcHealthInternalToolsEventFalcoEvent","MlcHealthMessagingLightswitchEventFalcoEvent","MlcHealthWorkplaceEventFalcoEvent","react"],(function(a,b,c,d,e,f,g){"use strict";var h,i=(h||d("react")).useLayoutEffect,j=new Set();function k(a){switch(a){case"facebook":return c("MlcHealthFacebookEventFalcoEvent");case"workplace":return c("MlcHealthWorkplaceEventFalcoEvent");case"facebook_and_workplace":return c("MlcHealthFacebookAndWorkplaceEventFalcoEvent");case"internal_tools":return c("MlcHealthInternalToolsEventFalcoEvent");case"messaging_lightswitch":return c("MlcHealthMessagingLightswitchEventFalcoEvent");case"bizapp":return c("MlcHealthBizappEventFalcoEvent");case"instagram":return c("MlcHealthInstagramEventFalcoEvent");default:return null}}function l(a,b,c){(a=k(a))==null?void 0:a.log(function(){return{event:c,surface:b}})}function a(a){var b=a.editor__DEPRECATED,c=a.policyProduct,e=a.surface,f;if(b)f=b;else{a=d("LexicalComposerContext").useLexicalComposerContext();f=a[0]}i(function(){var a=function(){};j.has(e)||(a=f.registerUpdateListener(function(b){var d=b.dirtyLeaves;b=b.tags;if(j.has(e)){a();return}if(d.size===0||b.has("history-merge")||!f.isEditable())return;j.add(e);l(c,e,"daily_interaction_with_surface");a()}));return d("LexicalUtils").mergeRegister(a,f.registerCommand(d("MLCInstrumentationCommands").COMMIT_COMMAND,function(a){a==="create"?l(c,e,"commit_create"):l(c,e,"commit_edit");return!1},d("Lexical").COMMAND_PRIORITY_CRITICAL))},[f,c,e]);return null}g["default"]=a}),98);
__d("MLCInteractionInstrumentationPlugin__INTERNAL.react",["cr:3286","react"],(function(a,b,c,d,e,f,g){"use strict";var h,i=h||d("react");function a(a){return b("cr:3286")&&i.jsx(b("cr:3286"),babelHelpers["extends"]({},a))}a.displayName=a.name+" [from "+f.id+"]";g["default"]=a}),98);
__d("MLCTypingPerformancePlugin__INTERNAL.react",["LexicalComposerContext","LexicalText","cr:2012305","cr:308","cr:3287","cr:5452","react"],(function(a,b,c,d,e,f,g){"use strict";var h,i=h||(h=d("react")),j=h.useLayoutEffect,k=b("cr:2012305")||b("cr:308");e=(c=b("cr:5452"))!=null?c:{};var l=e.getTextLengthBucket;function a(a){if(k===null)return null;b("cr:3287")&&b("cr:3287")();return i.jsx(m,babelHelpers["extends"]({},a))}a.displayName=a.name+" [from "+f.id+"]";function m(a){var b=a.editor__DEPRECATED,c=a.format__DEPRECATED,e=a.surface;a=a.typingPerformanceID;var f=a===void 0?"":a,g;if(b)g=b;else{a=d("LexicalComposerContext").useLexicalComposerContext();g=a[0]}j(function(){var a=babelHelpers["extends"]({},l==null?null:{textLengthBucket:l(g.getEditorState().read(d("LexicalText").$rootTextContent).length)}),b;h();function h(){b==null?void 0:b();if(k===null)return;var d=null,h=g.registerRootListener(function(b){if(b===d)return;d!==null&&k.unregisterTypingPerf(d);if(b!==null){var g;k.trackTypingPerf(b,e,d,babelHelpers["extends"]({},a,{editor:"LexicalEditor",format:(g=c)!=null?g:"",typingPerformanceID:f}))}d=b});b=function(){h(),d!==null&&k.unregisterTypingPerf(d)}}var i=l==null?null:g.registerTextContentListener(function(b){b=l(b.length);if(b===a.textLengthBucket)return;a.textLengthBucket=b;h()});return function(){b==null?void 0:b(),i==null?void 0:i()}},[f,g,c,e]);return null}m.displayName=m.name+" [from "+f.id+"]";g["default"]=a}),98);
__d("MLCInstrumentationPlugin__INTERNAL.react",["MLCHealthInstrumentationPlugin__INTERNAL.react","MLCInteractionInstrumentationPlugin__INTERNAL.react","MLCTypingPerformancePlugin__INTERNAL.react","react"],(function(a,b,c,d,e,f,g){"use strict";var h,i=h||d("react");b="facebook";b;function a(a){return i.jsxs(i.Fragment,{children:[i.jsx(c("MLCTypingPerformancePlugin__INTERNAL.react"),babelHelpers["extends"]({},a)),i.jsx(c("MLCHealthInstrumentationPlugin__INTERNAL.react"),babelHelpers["extends"]({},a)),i.jsx(c("MLCInteractionInstrumentationPlugin__INTERNAL.react"),babelHelpers["extends"]({},a))]})}a.displayName=a.name+" [from "+f.id+"]";g["default"]=a}),98);